### ISSUE TITLE
OTA not working

### ISSUE THREAD

**Issue by j2242** [bruhautomation/ESP-MQTT-JSON-Digital-LEDs#100]
When I plug everything in I get this error

Sketch uses 304800 bytes (29%) of program storage space. Maximum is 1044464 bytes.
Global variables use 32040 bytes (39%) of dynamic memory, leaving 49880 bytes for local variables. Maximum is 81920 bytes.
java.io.IOException: Cannot run program "python.exe": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:26)
	at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	at cc.arduino.packages.uploaders.GenericNetworkUploader.uploadUsingPreferences(GenericNetworkUploader.java:99)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:82)
	at processing.app.SketchController.upload(SketchController.java:736)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2028)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more

Ideas?

**Comment by denvansanten** [comment]
Might be an old issue but i fixed this by setting the path to python.exe on my windows computer.

- Tap windows key and type "system" (or go to windows config ->system & security -> system)
- click on "advanced settings" in the left menu
- In the advanced settings tab click on "enviroment variables"
- In the bottom section you will see "system variables"
- Click on "path", en select "edit"
- Double click on a new empty line on the bottom and type the path to your python.exe (for example "C:\Python27\"
- Click save and restart arduinoIDE and OTA should work
